### ISSUE TITLE
about imagenet_pretrian.py

### ISSUE THREAD

**Issue by HIHIHAHEI** [sunpeng1996/DSA2F#4]
Hi,Thanks for your code

Could you please reply what dataset you use in imagenet_pretrian.py?

![image](https://user-images.githubusercontent.com/40845081/123962080-a55bea00-d9e3-11eb-9004-4c732d7978fa.png)

Thanks!

**Comment by sunpeng1996** [comment]
It's just the ImageNet dataset for pretraining.

**Comment by HIHIHAHEI** [comment]
All of them? This dataset is very large. How long does it take to pretrain?
